#ifndef TOKENIZER_SM_H_INCLUDED
#define TOKENIZER_SM_H_INCLUDED

//! The tokenizer state machine. Generated by re2c

typedef enum TokenKind_e {
  INVALID, EOF, IDENTIFIER, L_PAREN, R_PAREN
} TokenKind;

//! given a reference to the tokenizer cursor
//! we find the next tokenkind and update
//! the cursor

TokenKind next_token(const char** tokenizer_cursor);

#endif //TOKENIZER_SM_H_INCLUDED 
